name: Send FCM Notifications

# üö´ Prevent duplicate and auto-retriggered runs
concurrency:
  group: notification-run
  cancel-in-progress: true

on:
  schedule:
    - cron: "*/15 * * * *"   # Every 15 minutes
  workflow_dispatch:          # Manual trigger

jobs:
  run-notifications:
    runs-on: ubuntu-latest
    timeout-minutes: 3        # ‚è± Stop auto retries after 60 min

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run notification script
        run: node notification.js
        env:
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
